include: package:lint/analysis_options.yaml

analyzer:
  errors:
    prefer_single_quotes: error
    prefer_const_constructors: error
    avoid_unnecessary_containers: error
    constant_identifier_names: warn
    avoid_print: error


linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    avoid_unnecessary_containers: true
    constant_identifier_names: false
    avoid_print: true