include: package:lint/analysis_options.yaml

analyzer:
  errors:
    avoid_print: error
    prefer_single_quotes: error


linter:
  rules:
    avoid_classes_with_only_static_members: false
    avoid_print: true
    prefer_single_quotes: true


