name: flutter_a2z
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  toast: ^0.1.5 #05-01-2021
  url_launcher: ^5.7.10  #17-01-2021
  flutter_syntax_view: ^2.2.2 #17-01-2021
  flutter_speed_dial: ^1.2.5 #18-01-2021
  intl: ^0.16.1 #24-01-2021
  giffy_dialog: ^1.8.0 #24-01-2021
  rotated_corner_decoration: ^1.0.2 #13-02-2021
  local_auth: ^0.6.3+4 #15-02-2021
  flutter_reaction_button: ^1.0.7+3 #25-02-2021
  grouped_list: ^3.7.1 #01-03-2021
  auto_size_text: ^2.1.0 #07-03-2021
  carousel_slider: ^3.0.0 #14-03-2021
  reorderables: #21-03-2021
  webview_flutter: any #22-03-2021
  flutter_html: any #22-03-2021
  image_picker: any #29-03-2021
  faker: any #30-03-2021
  email_validator: any #31-03-2021
  chips_input: any #02-04-2021
  animated_text_kit: ^4.2.1 #12-06-2021
  json_annotation: 3.1.1 #22-06-2021

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any #21-01-2021
  build_runner:
  json_serializable: 3.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - lib/screens/flutter_widgets/buttons/
    - lib/screens/flutter_widgets/buttons/my_toggle_button/
    - lib/screens/flutter_widgets/buttons/my_radio_button/
    - lib/screens/flutter_lifecycle/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf