class SyncfusionFlutterDataGridModel {
  int id;
  String name;
  String fullName;
  String department;
  String designation;
  String address;
  String joiningDate;
  int experience;

  SyncfusionFlutterDataGridModel({
    required this.id,
    required this.name,
    required this.fullName,
    required this.department,
    required this.designation,
    required this.address,
    required this.joiningDate,
    required this.experience,
  });

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'fullName': fullName,
        'department': department,
        'designation': designation,
        'address': address,
        'joiningDate': joiningDate,
        'experience': experience,
      };

  static List<SyncfusionFlutterDataGridModel> fetchAll() {
    return [
      SyncfusionFlutterDataGridModel(
        id: 1000,
        name: 'ruhul',
        fullName: 'Md. Ruhul Amin',
        department: 'Software Development',
        designation: 'Programmer',
        address: 'Naogaon',
        joiningDate: '01-12-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1001,
        name: 'arif',
        fullName: 'Md. Ariful Islam',
        department: 'Software Development',
        designation: 'Programmer',
        address: 'Dhaka, Mirpur',
        joiningDate: '01-12-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1002,
        name: 'zakaria',
        fullName: 'Ahamed Zakaria',
        department: 'Software Development',
        designation: 'Senior Programmer',
        address: 'Gazipur, Dhaka',
        joiningDate: '01-12-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1003,
        name: 'shariful',
        fullName: 'Md. Shariful Islam',
        department: 'Software Development',
        designation: 'Senior Programmer',
        address: 'Nohakhali',
        joiningDate: '01-01-2020',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1004,
        name: 'farid',
        fullName: 'Md. Farid Ahmed',
        department: 'Software Development',
        designation: 'Senior Programmer',
        address: 'Perizpur, Barishal',
        joiningDate: '12-01-2016',
        experience: 6,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1005,
        name: 'mezbah',
        fullName: 'Md. Mezbah Redawan',
        department: 'Software Development',
        designation: 'Project Manager',
        address: 'Jassore',
        joiningDate: '12-01-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1006,
        name: 'ruhul',
        fullName: 'Md. Ruhul Amin',
        department: 'Software Development',
        designation: 'Programmer',
        address: 'Naogaon',
        joiningDate: '01-12-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1007,
        name: 'arif',
        fullName: 'Md. Ariful Islam',
        department: 'Software Development',
        designation: 'Programmer',
        address: 'Dhaka, Mirpur',
        joiningDate: '01-12-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1008,
        name: 'zakaria',
        fullName: 'Ahamed Zakaria',
        department: 'Software Development',
        designation: 'Senior Programmer',
        address: 'Gazipur, Dhaka',
        joiningDate: '01-12-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1009,
        name: 'shariful',
        fullName: 'Md. Shariful Islam',
        department: 'Software Development',
        designation: 'Senior Programmer',
        address: 'Nohakhali',
        joiningDate: '01-01-2020',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1010,
        name: 'farid',
        fullName: 'Md. Farid Ahmed',
        department: 'Software Development',
        designation: 'Senior Programmer',
        address: 'Perizpur, Barishal',
        joiningDate: '12-01-2016',
        experience: 6,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1011,
        name: 'mezbah',
        fullName: 'Md. Mezbah Redawan',
        department: 'Software Development',
        designation: 'Project Manager',
        address: 'Jassore',
        joiningDate: '12-01-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1012,
        name: 'ruhul',
        fullName: 'Md. Ruhul Amin',
        department: 'Software Development',
        designation: 'Programmer',
        address: 'Naogaon',
        joiningDate: '01-12-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1013,
        name: 'arif',
        fullName: 'Md. Ariful Islam',
        department: 'Software Development',
        designation: 'Programmer',
        address: 'Dhaka, Mirpur',
        joiningDate: '01-12-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1014,
        name: 'zakaria',
        fullName: 'Ahamed Zakaria',
        department: 'Software Development',
        designation: 'Senior Programmer',
        address: 'Gazipur, Dhaka',
        joiningDate: '01-12-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1015,
        name: 'shariful',
        fullName: 'Md. Shariful Islam',
        department: 'Software Development',
        designation: 'Senior Programmer',
        address: 'Nohakhali',
        joiningDate: '01-01-2020',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1016,
        name: 'ruhul',
        fullName: 'Md. Ruhul Amin',
        department: 'Software Development',
        designation: 'Programmer',
        address: 'Naogaon',
        joiningDate: '01-12-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1017,
        name: 'arif',
        fullName: 'Md. Ariful Islam',
        department: 'Software Development',
        designation: 'Programmer',
        address: 'Dhaka, Mirpur',
        joiningDate: '01-12-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1018,
        name: 'zakaria',
        fullName: 'Ahamed Zakaria',
        department: 'Software Development',
        designation: 'Senior Programmer',
        address: 'Gazipur, Dhaka',
        joiningDate: '01-12-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1019,
        name: 'farid',
        fullName: 'Md. Farid Ahmed',
        department: 'Software Development',
        designation: 'Senior Programmer',
        address: 'Perizpur, Barishal',
        joiningDate: '12-01-2016',
        experience: 6,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1020,
        name: 'mezbah',
        fullName: 'Md. Mezbah Redawan',
        department: 'Software Development',
        designation: 'Project Manager',
        address: 'Jassore',
        joiningDate: '12-01-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1021,
        name: 'ruhul',
        fullName: 'Md. Ruhul Amin',
        department: 'Software Development',
        designation: 'Programmer',
        address: 'Naogaon',
        joiningDate: '01-12-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1022,
        name: 'arif',
        fullName: 'Md. Ariful Islam',
        department: 'Software Development',
        designation: 'Programmer',
        address: 'Dhaka, Mirpur',
        joiningDate: '01-12-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1023,
        name: 'zakaria',
        fullName: 'Ahamed Zakaria',
        department: 'Software Development',
        designation: 'Senior Programmer',
        address: 'Gazipur, Dhaka',
        joiningDate: '01-12-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1024,
        name: 'shariful',
        fullName: 'Md. Shariful Islam',
        department: 'Software Development',
        designation: 'Senior Programmer',
        address: 'Nohakhali',
        joiningDate: '01-01-2020',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1025,
        name: 'farid',
        fullName: 'Md. Farid Ahmed',
        department: 'Software Development',
        designation: 'Senior Programmer',
        address: 'Perizpur, Barishal',
        joiningDate: '12-01-2016',
        experience: 6,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1026,
        name: 'mezbah',
        fullName: 'Md. Mezbah Redawan',
        department: 'Software Development',
        designation: 'Project Manager',
        address: 'Jassore',
        joiningDate: '12-01-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1027,
        name: 'ruhul',
        fullName: 'Md. Ruhul Amin',
        department: 'Software Development',
        designation: 'Programmer',
        address: 'Naogaon',
        joiningDate: '01-12-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1028,
        name: 'arif',
        fullName: 'Md. Ariful Islam',
        department: 'Software Development',
        designation: 'Programmer',
        address: 'Dhaka, Mirpur',
        joiningDate: '01-12-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1029,
        name: 'zakaria',
        fullName: 'Ahamed Zakaria',
        department: 'Software Development',
        designation: 'Senior Programmer',
        address: 'Gazipur, Dhaka',
        joiningDate: '01-12-2019',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1030,
        name: 'shariful',
        fullName: 'Md. Shariful Islam',
        department: 'Software Development',
        designation: 'Senior Programmer',
        address: 'Nohakhali',
        joiningDate: '01-01-2020',
        experience: 2,
      ),
      SyncfusionFlutterDataGridModel(
        id: 1031,
        name: 'shariful',
        fullName: 'Md. Shariful Islam',
        department: 'Software Development',
        designation: 'Senior Programmer',
        address: 'Nohakhali',
        joiningDate: '01-01-2020',
        experience: 2,
      ),
    ];
  }
}
