import 'package:flutter_a2z/routing/routing_constants.dart';

class FlutterPackagesModel {
  String name;
  String packageName;
  bool nullSafe;
  String description;
  String? documentation;
  String packageLink;
  String youTubeLink;
  String gitLink;

  FlutterPackagesModel({
    required this.name,
    required this.packageName,
    required this.nullSafe,
    required this.description,
    required this.documentation,
    required this.packageLink,
    required this.youTubeLink,
    required this.gitLink,
  });

  static List<FlutterPackagesModel> fetchAll() => <FlutterPackagesModel>[
        FlutterPackagesModel(
          name: fontAwesomeFlutterTitle,
          packageName: 'font_awesome_flutter',
          nullSafe: true,
          description: 'The Font Awesome Icon pack available as Flutter Icons. Provides 1600 additional icons to use in your apps.',
          packageLink: 'https://pub.dev/packages/font_awesome_flutter',
          youTubeLink: 'https://www.youtube.com/watch?v=TOAyjIAsT7o',
          documentation: '',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: curvedNavigationBarTitle,
          packageName: 'curved_navigation_bar ',
          nullSafe: true,
          description: 'Stunning Animating Curved Shape Navigation Bar. Adjustable color, background color, animation curve, animation duration.',
          packageLink: 'https://pub.dev/packages/curved_navigation_bar',
          youTubeLink: 'https://www.youtube.com/watch?v=TX2x41h47fE&t=0s',
          documentation: '',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: filePickerTitle,
          packageName: 'file_picker',
          nullSafe: true,
          description: 'A package that allows you to use a native file explorer to pick single or multiple absolute file paths, with extension filtering support',
          packageLink: 'https://pub.dev/packages/file_picker',
          youTubeLink: 'https://www.youtube.com/watch?v=LlO5jydXws0&t=0s',
          documentation: '',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: storeRedirectTitle,
          packageName: 'store_redirect',
          nullSafe: true,
          description: 'A Flutter plugin to redirect users to an app page in Google Play Store and Apple App Store.',
          packageLink: 'https://pub.dev/packages/store_redirect',
          youTubeLink: 'https://www.youtube.com/watch?v=MYIPz71j7yc',
          documentation: '',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: urlLauncherTitle,
          packageName: 'url_launcher',
          nullSafe: true,
          description: 'Flutter plugin for launching a URL. Supports web, phone, SMS, and email schemes.',
          packageLink: 'https://pub.dev/packages/store_redirect',
          youTubeLink: 'https://www.youtube.com/watch?v=MYIPz71j7yc',
          documentation: '',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: syncfusionFlutterDataGridTitle,
          packageName: 'syncfusion_flutter_data_grid',
          nullSafe: true,
          description:
              'The Syncfusion Flutter DataGrid is used to display and manipulate data in a tabular view. Its rich feature set includes different types of columns, selections, column sizing, etc.',
          documentation: 'https://www.syncfusion.com/flutter-widgets/flutter-datagrid',
          packageLink: 'https://pub.dev/packages/syncfusion_flutter_datagrid',
          youTubeLink: 'https://www.youtube.com/watch?v=-ULsEfjxFuY&t=441s',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: horizontalDataTableTitle,
          packageName: 'horizontal_data_table',
          nullSafe: true,
          description: 'A horizontal data table with a fixed column on left hand side',
          documentation: '',
          packageLink: 'https://pub.dev/packages/horizontal_data_table',
          youTubeLink: '',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: connectivityPlusTitle,
          packageName: 'connectivity_plus',
          nullSafe: true,
          description: 'Flutter plugin for discovering the state of the network (WiFi & mobile/cellular) connectivity on Android and iOS.',
          documentation: 'https://pub.dev/documentation/connectivity_plus/latest/',
          packageLink: 'https://pub.dev/packages/connectivity_plus',
          youTubeLink: '',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: networkInfoPlusTitle,
          packageName: 'network_info_plus',
          nullSafe: true,
          description: 'Flutter plugin for discovering information (e.g. WiFi details) of the network.',
          documentation: 'https://pub.dev/documentation/connectivity_plus/latest/',
          packageLink: 'https://pub.dev/packages/connectivity_plus',
          youTubeLink: '',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: telephonyTitle,
          packageName: 'telephony',
          nullSafe: true,
          description: 'A Flutter plugin to use telephony features such as fetch network info, start phone calls, send and receive SMS, and listen for incoming SMS.',
          documentation: 'https://pub.dev/documentation/telephony/latest/',
          packageLink: 'https://pub.dev/packages/telephony',
          youTubeLink: '',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: deviceInfoPlusTitle,
          packageName: 'device_info_plus',
          nullSafe: true,
          description: 'Flutter plugin providing detailed information about the device (make, model, etc.), and Android or iOS version the app is running on.',
          documentation: 'https://pub.dev/documentation/device_info_plus/latest/',
          packageLink: 'https://pub.dev/packages/device_info_plus',
          youTubeLink: '',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: packageInfoPlusTitle,
          packageName: 'package_info_plus',
          nullSafe: true,
          description: 'You can use the PackageInfo to query information about the application package. This works both on iOS and Android.',
          documentation: 'https://pub.dev/documentation/package_info_plus/latest/',
          packageLink: 'https://pub.dev/packages/package_info_plus',
          youTubeLink: '',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: rotatedCornerDecorationTitle,
          packageName: 'rotated_corner_decoration',
          nullSafe: true,
          description: 'RotatedCornerDecoration package was developed to create and apply corner triangle badges. It provides auto rotation of TextSpans.',
          documentation: 'https://pub.dev/documentation/rotated_corner_decoration/latest/',
          packageLink: 'https://pub.dev/packages/rotated_corner_decoration',
          youTubeLink: '',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: speechToTextTitle,
          packageName: 'speech_to_text',
          nullSafe: true,
          description: 'A Flutter plugin that exposes device specific speech to text recognition capability.',
          documentation: 'https://pub.dev/documentation/speech_to_text/latest/',
          packageLink: 'https://pub.dev/packages/speech_to_text',
          youTubeLink: '',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: huaweiLocationTitle,
          packageName: 'huawei_location',
          nullSafe: true,
          description:
              '''Huawei Location Kit combines the Global Navigation Satellite System (GNSS), Wi-Fi, and base station location functionalities into your app to build up global positioning capabilities, allowing you to provide flexible location-based services for global users. Currently, it provides three main capabilities: fused location, activity identification, and geofence. You can call one or more of these capabilities as needed.''',
          documentation: 'https://pub.dev/documentation/huawei_location/latest/',
          packageLink: 'https://pub.dev/packages/huawei_location',
          youTubeLink: 'https://youtu.be/X1SkTGm4Xos',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: syncfusionFlutterGaugesTitle,
          packageName: 'syncfusion_flutter_gauges',
          nullSafe: true,
          description: '''The Flutter gauges library includes a linear gauge and radial gauge (a.k.a. circular gauge) to create modern, interactive, animated gauges and radial sliders.''',
          documentation: 'https://pub.dev/documentation/syncfusion_flutter_gauges/latest/',
          packageLink: 'https://pub.dev/packages/syncfusion_flutter_gauges',
          youTubeLink: 'https://youtu.be/2NuipO7j2tA',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: flutterHoloDatePickerTitle,
          packageName: 'flutter_holo_date_picker',
          nullSafe: true,
          description: '''A Flutter package of Datepicker that looks like Holo Theme in Android.''',
          documentation: 'https://pub.dev/documentation/flutter_holo_date_picker/latest/',
          packageLink: 'https://pub.dev/packages/flutter_holo_date_picker',
          youTubeLink: '',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: flutterHeatMapTitle,
          packageName: 'flutter_heat_map',
          nullSafe: true,
          description: '''Customizable heat map interface library. From a base image, it is necessary to pass the coordinates of the events and the library returns the image with the heat map''',
          documentation: 'https://pub.dev/documentation/flutter_heat_map/latest/',
          packageLink: 'https://pub.dev/packages/flutter_heat_map',
          youTubeLink: '',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: wifiIotTitle,
          packageName: 'wifi_iot',
          nullSafe: true,
          description: '''Flutter plugin which can handle WiFi connections and hotspot (AP, STA)''',
          documentation: 'https://pub.dev/documentation/wifi_iot/latest/',
          packageLink: 'https://pub.dev/packages/wifi_iot',
          youTubeLink: '',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: flutterCountdownTimerTitle,
          packageName: 'flutter_countdown_timer',
          nullSafe: true,
          description: '''A simple flutter countdown timer widget.Count down through the end timestamp,Trigger an event after the countdown ends.''',
          documentation: 'https://pub.dev/packages/flutter_countdown_timer/latest/',
          packageLink: 'https://pub.dev/packages/flutter_countdown_timer',
          youTubeLink: '',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: permissionHandlerTitle,
          packageName: 'permission_handler',
          nullSafe: true,
          description: '''Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions.''',
          documentation: 'https://pub.dev/documentation/permission_handler/latest/',
          packageLink: 'https://pub.dev/packages/permission_handler',
          youTubeLink: '',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: flutterBarcodeScannerTitle,
          packageName: 'flutter_barcode_scanner',
          nullSafe: true,
          description: '''A plugin for barcode scanning support on Android and iOS. Supports barcodes, QR codes, etc.''',
          documentation: 'https://pub.dev/documentation/flutter_barcode_scanner/latest/',
          packageLink: 'https://pub.dev/packages/flutter_barcode_scanner',
          youTubeLink: '',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: flutterPhotoViewTitle,
          packageName: 'photo_view',
          nullSafe: true,
          description: '''Photo View provides a gesture sensitive zoomable widget. Photo View is largely used to show interactive images and other stuff such as SVG.''',
          documentation: 'https://pub.dev/documentation/photo_view/latest/',
          packageLink: 'https://pub.dev/packages/photo_view',
          youTubeLink: 'https://www.youtube.com/watch?v=iP8WNXEB_ow',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: flutterCameraTitle,
          packageName: 'camera',
          nullSafe: true,
          description: '''A Flutter plugin for controlling the camera. Supports previewing the camera feed, capturing images and video, and streaming image buffers to Dart.''',
          documentation: 'https://pub.dev/documentation/camera/latest/',
          packageLink: 'https://pub.dev/packages/camera',
          youTubeLink: '',
          gitLink: '',
        ),
        FlutterPackagesModel(
          name: imagePickerTitle,
          packageName: 'image_picker',
          nullSafe: true,
          description: '''Flutter plugin for selecting images from the Android and iOS image library, and taking new pictures with the camera.''',
          documentation: 'https://pub.dev/documentation/image_picker/latest/',
          packageLink: 'https://pub.dev/packages/image_picker',
          youTubeLink: '',
          gitLink: '',
        ),
      ];
}
